#!/usr/bin/python

import dbus
import dbus.exceptions
import dbus.mainloop.glib
import dbus.service

try:
    from gi.repository import GObject  # python3
except ImportError:
    import gobject as GObject  # python2

mainloop = None

MULBERRY_SERVICE_NAME = 'io.mulberry'
MANAGER_IFACE = 'io.mulberry.Manager'
DEVICE_IFACE = 'io.mulberry.Device'
RESOURCE_IFACE = 'io.mulberry.Resource'

DBUS_OM_IFACE = 'org.freedesktop.DBus.ObjectManager'
DBUS_PROP_IFACE = 'org.freedesktop.DBus.Properties'

def main():
    global mainloop

    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

    bus = dbus.SystemBus()

    manager = dbus.Interface(bus.get_object(MULBERRY_SERVICE_NAME, '/'), MANAGER_IFACE)

    # Add sample device
    # - name, device type
    path = manager.AddDevice("myclient", "client", "oic.wk.d")

    manager.StartService()
    mainloop = GObject.MainLoop()
    mainloop.run()

if __name__ == '__main__':
    main()
